#!/bin/bash

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
# gruvbox-material.sh || catppuccin.sh
source "$CONFIG_DIR/colors.catppuccin.sh"

sketchybar --bar height=37 \
  blur_radius=30 \
  position=top \
  sticky=off \
  padding_left=10 \
  padding_right=10 \
  color=none \
  color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="JetBrains Mono:Bold:15.0" \
  label.font="JetBrains Mono:Bold:15.0" \
  background.corner_radius=5 \
  background.height=24 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=10 \
  label.padding_right=10 \
  icon.padding_left=4 \
  icon.padding_right=4
# icon.color=$ROSE100                 \
# label.color=$ROSE100                \
# background.color=$BCG       \

# LEFT Side items
#source $ITEM_DIR/spaces.sh

# source $ITEM_DIR/aerospace.sh
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  echo "sid = $sid icon=$ICON"
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=$PRIMARY \
    background.corner_radius=5 \
    label="$sid" \
    icon.drawing=on \
    background.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done
source $ITEM_DIR/front_app.sh

# right side of notch items
# Right Side items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/media.sh
# source $ITEM_DIR/keybattery.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

# label="$icon" \

sketchybar --update
